;;; -*- lexical-binding: t; -*-

;;; Commentary:

;;; This is a theme with simplicity in design.
;;;
;;; This theme highlights only the static structural information, which in my opinion makes reading code easier. Using too many colors makes everything distractive which is not good for everyday programming.
;;;
;;; All colors have similar contrast, which means we do not stress nor ignore any part of the text.  Comments should be conidered as much important as code.
;;;
;;; We do not make the whole theme blueish which is quite popular nowadays, because it makes looking at it more stressful.
;;;

;;; Code:

(deftheme carbon "A minimal, low contrast dark theme.")

(let ((cursor   "#ffffff")
      (black    "#211f17")
      (gray     "#d1cfc9")
      (darkgray "#424242")
      (white    "#d6d1cb")
      (red-1    "#d4967d")
      (red-2    "#d88361")
      (red-3    "#d15c47")
      (cyan-1   "#2ed1b6")
      (cyan-2   "#399183")
      (blue-1   "#4db6ea")
      (blue-2   "#4987e3")
      (green-1  "#52c448")
      (yellow-1 "#b3ad81")
      (yellow-2 "#ccc37c")
      (yellow-3 "#abb858")
      (purple-1 "#a99ad1")
      (purple-2 "#c19ad1"))
  (custom-theme-set-faces
   `carbon
   `(cursor ((t (:background ,cursor))))
   `(default ((t (:foreground ,white :background ,black))))
   `(region ((t (:foreground ,black :background ,gray))))
   `(Info-quoted ((t ())))
   `(abbrev-table-name ((t ())))
   `(ansi-color-black ((t ())))
   `(ansi-color-blue ((t ())))
   `(ansi-color-bold ((t ())))
   `(ansi-color-bright-black ((t ())))
   `(ansi-color-bright-blue ((t ())))
   `(ansi-color-bright-cyan ((t ())))
   `(ansi-color-bright-green ((t ())))
   `(ansi-color-bright-magenta ((t ())))
   `(ansi-color-bright-red ((t ())))
   `(ansi-color-bright-white ((t ())))
   `(ansi-color-bright-yellow ((t ())))
   `(ansi-color-cyan ((t ())))
   `(ansi-color-faint ((t ())))
   `(ansi-color-fast-blink ((t ())))
   `(ansi-color-green ((t (:foreground ,green-1))))
   `(ansi-color-inverse ((t ())))
   `(ansi-color-italic ((t ())))
   `(ansi-color-magenta ((t ())))
   `(ansi-color-red ((t ())))
   `(ansi-color-slow-blink ((t ())))
   `(ansi-color-underline ((t ())))
   `(ansi-color-white ((t ())))
   `(ansi-color-yellow ((t ())))
   `(blink-matching-paren-offscreen ((t ())))
   `(bold ((t ())))
   `(bold-italic ((t ())))
   `(border ((t ())))
   `(browse-url-button ((t ())))
   `(buffer-menu-buffer ((t ())))
   `(button ((t ())))
   `(calendar-month-header ((t ())))
   `(calendar-today ((t ())))
   `(calendar-weekday-header ((t ())))
   `(calendar-weekend-header ((t ())))
   `(change-log-acknowledgment ((t ())))
   `(change-log-conditionals ((t ())))
   `(change-log-date ((t ())))
   `(change-log-email ((t ())))
   `(change-log-file ((t ())))
   `(change-log-function ((t ())))
   `(change-log-list ((t ())))
   `(change-log-name ((t ())))
   `(child-frame-border ((t ())))
   `(comint-highlight-input ((t ())))
   `(comint-highlight-prompt ((t ())))
   `(company-echo ((t ())))
   `(company-echo-common ((t ())))
   `(company-preview ((t ())))
   `(company-preview-common ((t ())))
   `(company-preview-search ((t ())))
   `(company-tooltip ((t (:background ,darkgray))))
   `(company-tooltip-annotation ((t ())))
   `(company-tooltip-annotation-selection ((t ())))
   `(company-tooltip-common ((t ())))
   `(company-tooltip-common-selection ((t ())))
   `(company-tooltip-deprecated ((t ())))
   `(company-tooltip-mouse ((t ())))
   `(company-tooltip-quick-access ((t ())))
   `(company-tooltip-quick-access-selection ((t ())))
   `(company-tooltip-scrollbar-thumb ((t (:background ,gray))))
   `(company-tooltip-scrollbar-track ((t (:background ,darkgray))))
   `(company-tooltip-search ((t ())))
   `(company-tooltip-search-selection ((t ())))
   `(company-tooltip-selection ((t (:foreground ,black :background ,gray))))
   `(compilation-column-number ((t ())))
   `(compilation-error ((t ())))
   `(compilation-info ((t ())))
   `(compilation-line-number ((t ())))
   `(compilation-mode-line-exit ((t ())))
   `(compilation-mode-line-fail ((t ())))
   `(compilation-mode-line-run ((t ())))
   `(compilation-warning ((t ())))
   `(completions-annotations ((t ())))
   `(completions-common-part ((t ())))
   `(completions-first-difference ((t ())))
   `(completions-group-separator ((t ())))
   `(completions-group-title ((t ())))
   `(completions-highlight ((t ())))
   `(confusingly-reordered ((t ())))
   `(diary ((t ())))
   `(diff-added ((t ())))
   `(diff-changed ((t ())))
   `(diff-changed-unspecified ((t ())))
   `(diff-context ((t ())))
   `(diff-error ((t ())))
   `(diff-file-header ((t ())))
   `(diff-function ((t ())))
   `(diff-header ((t ())))
   `(diff-hunk-header ((t ())))
   `(diff-index ((t ())))
   `(diff-indicator-added ((t ())))
   `(diff-indicator-changed ((t ())))
   `(diff-indicator-removed ((t ())))
   `(diff-nonexistent ((t ())))
   `(diff-refine-added ((t ())))
   `(diff-refine-changed ((t ())))
   `(diff-refine-removed ((t ())))
   `(diff-removed ((t ())))
   `(dired-broken-symlink ((t ())))
   `(dired-directory ((t ())))
   `(dired-flagged ((t ())))
   `(dired-header ((t ())))
   `(dired-ignored ((t ())))
   `(dired-mark ((t ())))
   `(dired-marked ((t ())))
   `(dired-perm-write ((t ())))
   `(dired-set-id ((t ())))
   `(dired-special ((t ())))
   `(dired-symlink ((t ())))
   `(dired-warning ((t ())))
   `(doc-view-svg-face ((t ())))
   `(edmacro-label ((t ())))
   `(eldoc-highlight-function-argument ((t ())))
   `(elisp-shorthand-font-lock-face ((t ())))
   `(envrc-mode-line-error-face ((t ())))
   `(envrc-mode-line-none-face ((t ())))
   `(envrc-mode-line-on-face ((t ())))
   `(epa-field-body ((t ())))
   `(epa-field-name ((t ())))
   `(epa-mark ((t ())))
   `(epa-string ((t ())))
   `(epa-validity-disabled ((t ())))
   `(epa-validity-high ((t ())))
   `(epa-validity-low ((t ())))
   `(epa-validity-medium ((t ())))
   `(error ((t ())))
   `(escape-glyph ((t ())))
   `(eww-form-checkbox ((t ())))
   `(eww-form-file ((t ())))
   `(eww-form-select ((t ())))
   `(eww-form-submit ((t ())))
   `(eww-form-text ((t ())))
   `(eww-form-textarea ((t ())))
   `(eww-invalid-certificate ((t ())))
   `(eww-valid-certificate ((t ())))
   `(file-name-shadow ((t ())))
   `(fill-column-indicator ((t ())))
   `(fixed-pitch ((t ())))
   `(fixed-pitch-serif ((t ())))
   `(font-lock-bracket-face ((t ())))
   `(font-lock-builtin-face ((t ())))
   `(font-lock-comment-delimiter-face ((t (:foreground ,red-2))))
   `(font-lock-comment-face ((t (:foreground ,red-1))))
   `(font-lock-constant-face ((t (:foreground ,purple-1))))
   `(font-lock-delimiter-face ((t ())))
   `(font-lock-doc-face ((t ())))
   `(font-lock-doc-markup-face ((t ())))
   `(font-lock-escape-face ((t ())))
   `(font-lock-function-call-face ((t ())))
   `(font-lock-function-name-face ((t (:foreground ,green-1))))
   `(font-lock-keyword-face ((t (:foreground ,yellow-1))))
   `(font-lock-misc-punctuation-face ((t ())))
   `(font-lock-negation-char-face ((t ())))
   `(font-lock-number-face ((t (:foreground ,purple-2))))
   `(font-lock-operator-face ((t ())))
   `(font-lock-preprocessor-face ((t (:foreground ,yellow-2))))
   `(font-lock-property-name-face ((t ())))
   `(font-lock-property-use-face ((t ())))
   `(font-lock-punctuation-face ((t ())))
   `(font-lock-regexp-face ((t ())))
   `(font-lock-regexp-grouping-backslash ((t ())))
   `(font-lock-regexp-grouping-construct ((t ())))
   `(font-lock-string-face ((t (:foreground ,blue-1))))
   `(font-lock-type-face ((t ())))
   `(font-lock-variable-name-face ((t ())))
   `(font-lock-variable-use-face ((t ())))
   `(font-lock-warning-face ((t ())))
   `(fringe ((t ())))
   `(geiser-font-lock-autodoc-current-arg ((t ())))
   `(geiser-font-lock-autodoc-identifier ((t ())))
   `(geiser-font-lock-doc-button ((t ())))
   `(geiser-font-lock-doc-link ((t ())))
   `(geiser-font-lock-doc-title ((t ())))
   `(geiser-font-lock-error-link ((t ())))
   `(geiser-font-lock-image-button ((t ())))
   `(geiser-font-lock-repl-input ((t ())))
   `(geiser-font-lock-repl-output ((t ())))
   `(geiser-font-lock-repl-prompt ((t ())))
   `(geiser-font-lock-xref-header ((t ())))
   `(geiser-font-lock-xref-link ((t ())))
   `(git-commit-comment-action ((t ())))
   `(git-commit-comment-branch-local ((t ())))
   `(git-commit-comment-branch-remote ((t ())))
   `(git-commit-comment-detached ((t ())))
   `(git-commit-comment-file ((t ())))
   `(git-commit-comment-heading ((t ())))
   `(git-commit-keyword ((t ())))
   `(git-commit-nonempty-second-line ((t ())))
   `(git-commit-overlong-summary ((t ())))
   `(git-commit-summary ((t ())))
   `(git-commit-trailer-token ((t ())))
   `(git-commit-trailer-value ((t ())))
   `(glyphless-char ((t ())))
   `(gnus-button ((t ())))
   `(gnus-emphasis-bold ((t ())))
   `(gnus-emphasis-bold-italic ((t ())))
   `(gnus-emphasis-highlight-words ((t ())))
   `(gnus-emphasis-italic ((t ())))
   `(gnus-emphasis-strikethru ((t ())))
   `(gnus-emphasis-underline ((t ())))
   `(gnus-emphasis-underline-bold ((t ())))
   `(gnus-emphasis-underline-bold-italic ((t ())))
   `(gnus-emphasis-underline-italic ((t ())))
   `(gnus-group-mail-1 ((t ())))
   `(gnus-group-mail-1-empty ((t ())))
   `(gnus-group-mail-2 ((t ())))
   `(gnus-group-mail-2-empty ((t ())))
   `(gnus-group-mail-3 ((t ())))
   `(gnus-group-mail-3-empty ((t ())))
   `(gnus-group-mail-low ((t ())))
   `(gnus-group-mail-low-empty ((t ())))
   `(gnus-group-news-1 ((t ())))
   `(gnus-group-news-1-empty ((t ())))
   `(gnus-group-news-2 ((t ())))
   `(gnus-group-news-2-empty ((t ())))
   `(gnus-group-news-3 ((t ())))
   `(gnus-group-news-3-empty ((t ())))
   `(gnus-group-news-4 ((t ())))
   `(gnus-group-news-4-empty ((t ())))
   `(gnus-group-news-5 ((t ())))
   `(gnus-group-news-5-empty ((t ())))
   `(gnus-group-news-6 ((t ())))
   `(gnus-group-news-6-empty ((t ())))
   `(gnus-group-news-low ((t ())))
   `(gnus-group-news-low-empty ((t ())))
   `(gnus-header ((t ())))
   `(gnus-header-content ((t ())))
   `(gnus-header-from ((t ())))
   `(gnus-header-name ((t ())))
   `(gnus-header-newsgroups ((t ())))
   `(gnus-header-subject ((t ())))
   `(gnus-signature ((t ())))
   `(gnus-splash ((t ())))
   `(gnus-summary-cancelled ((t ())))
   `(gnus-summary-high-ancient ((t ())))
   `(gnus-summary-high-read ((t ())))
   `(gnus-summary-high-ticked ((t ())))
   `(gnus-summary-high-undownloaded ((t ())))
   `(gnus-summary-high-unread ((t ())))
   `(gnus-summary-low-ancient ((t ())))
   `(gnus-summary-low-read ((t ())))
   `(gnus-summary-low-ticked ((t ())))
   `(gnus-summary-low-undownloaded ((t ())))
   `(gnus-summary-low-unread ((t ())))
   `(gnus-summary-normal-ancient ((t ())))
   `(gnus-summary-normal-read ((t ())))
   `(gnus-summary-normal-ticked ((t ())))
   `(gnus-summary-normal-undownloaded ((t ())))
   `(gnus-summary-normal-unread ((t ())))
   `(gnus-summary-selected ((t ())))
   `(header-line ((t ())))
   `(header-line-active ((t ())))
   `(header-line-highlight ((t ())))
   `(header-line-inactive ((t ())))
   `(help-argument-name ((t ())))
   `(help-for-help-header ((t ())))
   `(help-key-binding ((t ())))
   `(highlight ((t (:background ,darkgray))))
   `(highlight-numbers-number ((t (:inherit font-lock-number-face))))
   `(holiday ((t ())))
   `(homoglyph ((t ())))
   `(hs-ellipsis ((t ())))
   `(icon ((t ())))
   `(icon-button ((t ())))
   `(info-header-node ((t ())))
   `(info-header-xref ((t ())))
   `(info-index-match ((t ())))
   `(info-menu-header ((t ())))
   `(info-menu-star ((t ())))
   `(info-node ((t ())))
   `(info-title-1 ((t ())))
   `(info-title-2 ((t ())))
   `(info-title-3 ((t ())))
   `(info-title-4 ((t ())))
   `(info-xref ((t (:foreground ,cyan-1))))
   `(info-xref-visited ((t ())))
   `(internal-border ((t ())))
   `(isearch ((t ())))
   `(isearch-fail ((t ())))
   `(isearch-group-1 ((t ())))
   `(isearch-group-2 ((t ())))
   `(italic ((t ())))
   `(kmacro-menu-flagged ((t ())))
   `(kmacro-menu-mark ((t ())))
   `(kmacro-menu-marked ((t ())))
   `(lazy-highlight ((t (:inherit highlight))))
   `(line-number ((t ())))
   `(line-number-current-line ((t ())))
   `(line-number-major-tick ((t ())))
   `(line-number-minor-tick ((t ())))
   `(link ((t ())))
   `(link-visited ((t ())))
   `(llama-deleted-argument ((t ())))
   `(llama-llama-macro ((t ())))
   `(llama-mandatory-argument ((t ())))
   `(llama-optional-argument ((t ())))
   `(loccur-face ((t ())))
   `(log-edit-header ((t ())))
   `(log-edit-headers-separator ((t ())))
   `(log-edit-summary ((t ())))
   `(log-edit-unknown-header ((t ())))
   `(log-view-commit-body ((t ())))
   `(log-view-file ((t ())))
   `(log-view-message ((t ())))
   `(magit-bisect-bad ((t ())))
   `(magit-bisect-good ((t ())))
   `(magit-bisect-skip ((t ())))
   `(magit-blame-date ((t ())))
   `(magit-blame-dimmed ((t ())))
   `(magit-blame-hash ((t ())))
   `(magit-blame-heading ((t ())))
   `(magit-blame-highlight ((t ())))
   `(magit-blame-margin ((t ())))
   `(magit-blame-name ((t ())))
   `(magit-blame-summary ((t ())))
   `(magit-branch-current ((t (:foreground ,green-1))))
   `(magit-branch-local ((t (:foreground ,blue-1))))
   `(magit-branch-remote ((t (:foreground ,purple-1))))
   `(magit-branch-remote-head ((t ())))
   `(magit-branch-upstream ((t ())))
   `(magit-branch-warning ((t ())))
   `(magit-cherry-equivalent ((t ())))
   `(magit-cherry-unmatched ((t ())))
   `(magit-diff-added ((t (:foreground ,green-1))))
   `(magit-diff-added-highlight ((t (:foreground ,green-1))))
   `(magit-diff-base ((t ())))
   `(magit-diff-base-highlight ((t ())))
   `(magit-diff-conflict-heading ((t ())))
   `(magit-diff-context ((t ())))
   `(magit-diff-context-highlight ((t ())))
   `(magit-diff-file-heading ((t ())))
   `(magit-diff-file-heading-highlight ((t ())))
   `(magit-diff-file-heading-selection ((t ())))
   `(magit-diff-hunk-heading ((t (:foreground ,black :background ,gray))))
   `(magit-diff-hunk-heading-highlight ((t ())))
   `(magit-diff-hunk-heading-selection ((t ())))
   `(magit-diff-hunk-region ((t ())))
   `(magit-diff-lines-boundary ((t ())))
   `(magit-diff-lines-heading ((t ())))
   `(magit-diff-our ((t ())))
   `(magit-diff-our-highlight ((t ())))
   `(magit-diff-removed ((t (:foreground ,red-1))))
   `(magit-diff-removed-highlight ((t (:foreground ,red-1))))
   `(magit-diff-revision-summary ((t ())))
   `(magit-diff-revision-summary-highlight ((t ())))
   `(magit-diff-their ((t ())))
   `(magit-diff-their-highlight ((t ())))
   `(magit-diff-whitespace-warning ((t ())))
   `(magit-diffstat-added ((t ())))
   `(magit-diffstat-removed ((t ())))
   `(magit-dimmed ((t ())))
   `(magit-filename ((t ())))
   `(magit-hash ((t ())))
   `(magit-head ((t ())))
   `(magit-header-line ((t ())))
   `(magit-header-line-key ((t ())))
   `(magit-header-line-log-select ((t ())))
   `(magit-keyword ((t ())))
   `(magit-keyword-squash ((t ())))
   `(magit-log-author ((t ())))
   `(magit-log-date ((t ())))
   `(magit-log-graph ((t ())))
   `(magit-mode-line-process ((t ())))
   `(magit-mode-line-process-error ((t ())))
   `(magit-process-ng ((t ())))
   `(magit-process-ok ((t ())))
   `(magit-reflog-amend ((t ())))
   `(magit-reflog-checkout ((t ())))
   `(magit-reflog-cherry-pick ((t ())))
   `(magit-reflog-commit ((t ())))
   `(magit-reflog-merge ((t ())))
   `(magit-reflog-other ((t ())))
   `(magit-reflog-rebase ((t ())))
   `(magit-reflog-remote ((t ())))
   `(magit-reflog-reset ((t ())))
   `(magit-refname ((t ())))
   `(magit-refname-pullreq ((t ())))
   `(magit-refname-stash ((t ())))
   `(magit-refname-wip ((t ())))
   `(magit-section-child-count ((t ())))
   `(magit-section-heading ((t ())))
   `(magit-section-heading-selection ((t ())))
   `(magit-section-highlight ((t ())))
   `(magit-section-secondary-heading ((t ())))
   `(magit-sequence-done ((t ())))
   `(magit-sequence-drop ((t ())))
   `(magit-sequence-exec ((t ())))
   `(magit-sequence-head ((t ())))
   `(magit-sequence-onto ((t ())))
   `(magit-sequence-part ((t ())))
   `(magit-sequence-pick ((t ())))
   `(magit-sequence-stop ((t ())))
   `(magit-signature-bad ((t ())))
   `(magit-signature-error ((t ())))
   `(magit-signature-expired ((t ())))
   `(magit-signature-expired-key ((t ())))
   `(magit-signature-good ((t ())))
   `(magit-signature-revoked ((t ())))
   `(magit-signature-untrusted ((t ())))
   `(magit-tag ((t ())))
   `(match ((t ())))
   `(menu ((t ())))
   `(message-cited-text-1 ((t ())))
   `(message-cited-text-2 ((t ())))
   `(message-cited-text-3 ((t ())))
   `(message-cited-text-4 ((t ())))
   `(message-header-cc ((t ())))
   `(message-header-name ((t ())))
   `(message-header-newsgroups ((t ())))
   `(message-header-other ((t ())))
   `(message-header-subject ((t ())))
   `(message-header-to ((t ())))
   `(message-header-xheader ((t ())))
   `(message-mml ((t ())))
   `(message-separator ((t ())))
   `(message-signature-separator ((t ())))
   `(minibuffer-prompt ((t ())))
   `(mm-command-output ((t ())))
   `(mm-uu-extract ((t ())))
   `(mode-line ((t ())))
   `(mode-line-active ((t (:foreground ,black :background ,gray))))
   `(mode-line-buffer-id ((t ())))
   `(mode-line-emphasis ((t ())))
   `(mode-line-highlight ((t ())))
   `(mode-line-inactive ((t (:foreground ,white :background ,darkgray))))
   `(mouse ((t ())))
   `(mouse-drag-and-drop-region ((t ())))
   `(next-error ((t ())))
   `(next-error-message ((t ())))
   `(nil ((t ())))
   `(nobreak-hyphen ((t ())))
   `(nobreak-space ((t ())))
   `(org-agenda-calendar-daterange ((t ())))
   `(org-agenda-calendar-event ((t ())))
   `(org-agenda-calendar-sexp ((t ())))
   `(org-agenda-clocking ((t ())))
   `(org-agenda-column-dateline ((t ())))
   `(org-agenda-current-time ((t ())))
   `(org-agenda-date ((t ())))
   `(org-agenda-date-today ((t ())))
   `(org-agenda-date-weekend ((t ())))
   `(org-agenda-date-weekend-today ((t ())))
   `(org-agenda-diary ((t ())))
   `(org-agenda-dimmed-todo-face ((t ())))
   `(org-agenda-done ((t ())))
   `(org-agenda-filter-category ((t ())))
   `(org-agenda-filter-effort ((t ())))
   `(org-agenda-filter-regexp ((t ())))
   `(org-agenda-filter-tags ((t ())))
   `(org-agenda-restriction-lock ((t ())))
   `(org-agenda-structure ((t ())))
   `(org-agenda-structure-filter ((t ())))
   `(org-agenda-structure-secondary ((t ())))
   `(org-archived ((t ())))
   `(org-block ((t ())))
   `(org-block-begin-line ((t ())))
   `(org-block-end-line ((t ())))
   `(org-checkbox ((t ())))
   `(org-checkbox-statistics-done ((t ())))
   `(org-checkbox-statistics-todo ((t ())))
   `(org-cite ((t ())))
   `(org-cite-key ((t ())))
   `(org-clock-overlay ((t ())))
   `(org-code ((t ())))
   `(org-column ((t ())))
   `(org-column-title ((t ())))
   `(org-date ((t ())))
   `(org-date-selected ((t ())))
   `(org-default ((t ())))
   `(org-dispatcher-highlight ((t ())))
   `(org-document-info ((t ())))
   `(org-document-info-keyword ((t ())))
   `(org-document-title ((t ())))
   `(org-done ((t ())))
   `(org-drawer ((t ())))
   `(org-ellipsis ((t ())))
   `(org-footnote ((t ())))
   `(org-formula ((t ())))
   `(org-habit-alert-face ((t ())))
   `(org-habit-alert-future-face ((t ())))
   `(org-habit-clear-face ((t ())))
   `(org-habit-clear-future-face ((t ())))
   `(org-habit-overdue-face ((t ())))
   `(org-habit-overdue-future-face ((t ())))
   `(org-habit-ready-face ((t ())))
   `(org-habit-ready-future-face ((t ())))
   `(org-headline-done ((t (:foreground ,yellow-1))))
   `(org-headline-todo ((t (:foreground ,green-1))))
   `(org-hide ((t (:foreground ,black))))
   `(org-imminent-deadline ((t ())))
   `(org-indent ((t (:foreground ,black))))
   `(org-inline-src-block ((t ())))
   `(org-latex-and-related ((t ())))
   `(org-level-1 ((t ())))
   `(org-level-2 ((t ())))
   `(org-level-3 ((t ())))
   `(org-level-4 ((t ())))
   `(org-level-5 ((t ())))
   `(org-level-6 ((t ())))
   `(org-level-7 ((t ())))
   `(org-level-8 ((t ())))
   `(org-link ((t ())))
   `(org-list-dt ((t ())))
   `(org-macro ((t ())))
   `(org-meta-line ((t ())))
   `(org-mode-line-clock ((t ())))
   `(org-mode-line-clock-overrun ((t ())))
   `(org-priority ((t ())))
   `(org-property-value ((t ())))
   `(org-quote ((t ())))
   `(org-scheduled ((t ())))
   `(org-scheduled-previously ((t ())))
   `(org-scheduled-today ((t ())))
   `(org-sexp-date ((t ())))
   `(org-special-keyword ((t ())))
   `(org-table ((t ())))
   `(org-table-header ((t ())))
   `(org-table-row ((t ())))
   `(org-tag ((t ())))
   `(org-tag-group ((t ())))
   `(org-target ((t ())))
   `(org-time-grid ((t ())))
   `(org-todo ((t ())))
   `(org-upcoming-deadline ((t ())))
   `(org-upcoming-distant-deadline ((t ())))
   `(org-verbatim ((t ())))
   `(org-verse ((t ())))
   `(org-warning ((t ())))
   `(outline-1 ((t ())))
   `(outline-2 ((t ())))
   `(outline-3 ((t ())))
   `(outline-4 ((t ())))
   `(outline-5 ((t ())))
   `(outline-6 ((t ())))
   `(outline-7 ((t ())))
   `(outline-8 ((t ())))
   `(package-description ((t ())))
   `(package-help-section-name ((t ())))
   `(package-mark-delete-line ((t ())))
   `(package-mark-install-line ((t ())))
   `(package-mode-line-installed ((t ())))
   `(package-mode-line-new ((t ())))
   `(package-mode-line-to-upgrade ((t ())))
   `(package-mode-line-total ((t ())))
   `(package-name ((t ())))
   `(package-status-avail-obso ((t ())))
   `(package-status-available ((t ())))
   `(package-status-built-in ((t ())))
   `(package-status-dependency ((t ())))
   `(package-status-disabled ((t ())))
   `(package-status-external ((t ())))
   `(package-status-from-source ((t ())))
   `(package-status-held ((t ())))
   `(package-status-incompat ((t ())))
   `(package-status-installed ((t ())))
   `(package-status-new ((t ())))
   `(package-status-unsigned ((t ())))
   `(parenthesis ((t (:foreground ,cyan-2))))
   `(pass-mode-directory-face ((t ())))
   `(pass-mode-entry-face ((t ())))
   `(pass-mode-header-face ((t ())))
   `(pass-mode-keybinding-face ((t ())))
   `(prescient-primary-highlight ((t ())))
   `(prescient-secondary-highlight ((t ())))
   `(pulse-highlight-face ((t ())))
   `(pulse-highlight-start-face ((t ())))
   `(query-replace ((t ())))
   `(read-multiple-choice-face ((t ())))
   `(rectangle-preview ((t ())))
   `(scroll-bar ((t ())))
   `(secondary-selection ((t ())))
   `(separator-line ((t ())))
   `(sh-escaped-newline ((t ())))
   `(sh-heredoc ((t ())))
   `(sh-quoted-exec ((t ())))
   `(shadow ((t ())))
   `(shell-highlight-undef-alias-face ((t ())))
   `(shell-highlight-undef-defined-face ((t ())))
   `(shell-highlight-undef-undefined-face ((t ())))
   `(shortdoc-heading ((t ())))
   `(shortdoc-section ((t ())))
   `(show-paren-match ((t ())))
   `(show-paren-match-expression ((t ())))
   `(show-paren-mismatch ((t ())))
   `(shr-abbreviation ((t ())))
   `(shr-code ((t ())))
   `(shr-h1 ((t ())))
   `(shr-h2 ((t ())))
   `(shr-h3 ((t ())))
   `(shr-h4 ((t ())))
   `(shr-h5 ((t ())))
   `(shr-h6 ((t ())))
   `(shr-link ((t ())))
   `(shr-mark ((t ())))
   `(shr-selected-link ((t ())))
   `(shr-sliced-image ((t ())))
   `(shr-strike-through ((t ())))
   `(shr-sup ((t ())))
   `(shr-text ((t ())))
   `(smerge-base ((t ())))
   `(smerge-lower ((t ())))
   `(smerge-markers ((t ())))
   `(smerge-refine-shadow-cursor ((t ())))
   `(smerge-refined-added ((t ())))
   `(smerge-refined-changed ((t ())))
   `(smerge-refined-removed ((t ())))
   `(smerge-upper ((t ())))
   `(straight-process-command ((t ())))
   `(straight-process-error ((t ())))
   `(success ((t ())))
   `(tab-bar ((t ())))
   `(tab-bar-tab ((t ())))
   `(tab-bar-tab-group-current ((t ())))
   `(tab-bar-tab-group-inactive ((t ())))
   `(tab-bar-tab-highlight ((t ())))
   `(tab-bar-tab-inactive ((t ())))
   `(tab-bar-tab-ungrouped ((t ())))
   `(tab-line ((t ())))
   `(tabulated-list-fake-header ((t ())))
   `(tool-bar ((t ())))
   `(tooltip ((t ())))
   `(trailing-whitespace ((t ())))
   `(transient-active-infix ((t ())))
   `(transient-argument ((t ())))
   `(transient-delimiter ((t ())))
   `(transient-disabled-suffix ((t ())))
   `(transient-enabled-suffix ((t ())))
   `(transient-heading ((t ())))
   `(transient-higher-level ((t ())))
   `(transient-inactive-argument ((t ())))
   `(transient-inactive-value ((t ())))
   `(transient-inapt-suffix ((t ())))
   `(transient-key ((t ())))
   `(transient-key-exit ((t ())))
   `(transient-key-noop ((t ())))
   `(transient-key-return ((t ())))
   `(transient-key-stay ((t ())))
   `(transient-mismatched-key ((t ())))
   `(transient-nonstandard-key ((t ())))
   `(transient-unreachable ((t ())))
   `(transient-unreachable-key ((t ())))
   `(transient-value ((t ())))
   `(treesit-explorer-anonymous-node ((t ())))
   `(treesit-explorer-field-name ((t ())))
   `(tty-menu-disabled-face ((t ())))
   `(tty-menu-enabled-face ((t ())))
   `(tty-menu-selected-face ((t ())))
   `(underline ((t ())))
   `(variable-pitch ((t ())))
   `(variable-pitch-text ((t ())))
   `(vc-conflict-state ((t ())))
   `(vc-edited-state ((t ())))
   `(vc-git-log-edit-summary-max-warning ((t ())))
   `(vc-git-log-edit-summary-target-warning ((t ())))
   `(vc-ignored-state ((t ())))
   `(vc-locally-added-state ((t ())))
   `(vc-locked-state ((t ())))
   `(vc-missing-state ((t ())))
   `(vc-needs-update-state ((t ())))
   `(vc-removed-state ((t ())))
   `(vc-state-base ((t ())))
   `(vc-up-to-date-state ((t ())))
   `(vertical-border ((t ())))
   `(vertico-current ((t (:foreground ,black :background ,gray))))
   `(vertico-group-separator ((t ())))
   `(vertico-group-title ((t ())))
   `(vertico-multiline ((t ())))
   `(vtable ((t ())))
   `(warning ((t ())))
   `(which-func ((t ())))
   `(which-key-command-description-face ((t ())))
   `(which-key-docstring-face ((t ())))
   `(which-key-group-description-face ((t ())))
   `(which-key-highlighted-command-face ((t ())))
   `(which-key-key-face ((t ())))
   `(which-key-local-map-description-face ((t ())))
   `(which-key-note-face ((t ())))
   `(which-key-separator-face ((t ())))
   `(which-key-special-key-face ((t ())))
   `(widget-button ((t ())))
   `(widget-button-pressed ((t ())))
   `(widget-documentation ((t ())))
   `(widget-field ((t ())))
   `(widget-inactive ((t ())))
   `(widget-single-line-field ((t ())))
   `(widget-unselected ((t ())))
   `(window-divider ((t ())))
   `(window-divider-first-pixel ((t ())))
   `(window-divider-last-pixel ((t ())))
   `(xref-file-header ((t ())))
   `(xref-line-number ((t ())))
   `(xref-match ((t ())))
   `(yas--field-debug-face ((t ())))
   `(yas-field-highlight-face ((t ())))))

(and load-file-name
     (boundp 'custom-theme-load-path)
     (add-to-list 'custom-theme-load-path
                  (file-name-as-directory
                   (file-name-directory load-file-name))))

(provide-theme 'carbon)
;;; carbon-theme.el ends here
